package cn.cqautotest.sunnybeach.util

import cn.cqautotest.sunnybeach.R

/**
 * author : A Lonely Cat
 * github : https://github.com/anjiemo/SunnyBeach
 * time   : 2022/03/24
 * desc   : emoji 文字表情映射帮助类
 */
object EmojiMapHelper {

    // B站 emoji 表情映射集合
    val bilibiliEmojiMap = mapOf(
        "[微笑]" to R.mipmap.emoji_bilibili_001,
        "[呲牙]" to R.mipmap.emoji_bilibili_002,
        "[OK]" to R.mipmap.emoji_bilibili_003,
        "[星星眼]" to R.mipmap.emoji_bilibili_004,
        "[哦呼]" to R.mipmap.emoji_bilibili_005,
        "[歪嘴]" to R.mipmap.emoji_bilibili_006,
        "[嫌弃]" to R.mipmap.emoji_bilibili_007,
        "[喜欢]" to R.mipmap.emoji_bilibili_008,
        "[酸了]" to R.mipmap.emoji_bilibili_009,
        "[大哭]" to R.mipmap.emoji_bilibili_010,
        "[害羞]" to R.mipmap.emoji_bilibili_011,
        "[疑惑]" to R.mipmap.emoji_bilibili_012,
        "[辣眼睛]" to R.mipmap.emoji_bilibili_013,
        "[调皮]" to R.mipmap.emoji_bilibili_014,
        "[喜极而泣]" to R.mipmap.emoji_bilibili_015,
        "[奸笑]" to R.mipmap.emoji_bilibili_016,
        "[笑]" to R.mipmap.emoji_bilibili_017,
        "[偷笑]" to R.mipmap.emoji_bilibili_018,
        "[大笑]" to R.mipmap.emoji_bilibili_019,
        "[阴险]" to R.mipmap.emoji_bilibili_020,
        "[捂脸]" to R.mipmap.emoji_bilibili_021,
        "[囧]" to R.mipmap.emoji_bilibili_022,
        "[呆]" to R.mipmap.emoji_bilibili_023,
        "[抠鼻]" to R.mipmap.emoji_bilibili_024,
        "[惊喜]" to R.mipmap.emoji_bilibili_025,
        "[惊讶]" to R.mipmap.emoji_bilibili_026,
        "[笑哭]" to R.mipmap.emoji_bilibili_027,
        "[妙啊]" to R.mipmap.emoji_bilibili_028,
        "[doge]" to R.mipmap.emoji_bilibili_029,
        "[滑稽]" to R.mipmap.emoji_bilibili_030,
        "[吃瓜]" to R.mipmap.emoji_bilibili_031,
        "[打call]" to R.mipmap.emoji_bilibili_032,
        "[点赞]" to R.mipmap.emoji_bilibili_033,
        "[鼓掌]" to R.mipmap.emoji_bilibili_034,
        "[无语]" to R.mipmap.emoji_bilibili_035,
        "[尴尬]" to R.mipmap.emoji_bilibili_036,
        "[冷]" to R.mipmap.emoji_bilibili_037,
        "[灵魂出窍]" to R.mipmap.emoji_bilibili_038,
        "[委屈]" to R.mipmap.emoji_bilibili_039,
        "[傲娇]" to R.mipmap.emoji_bilibili_040,
        "[疼]" to R.mipmap.emoji_bilibili_041,
        "[吓]" to R.mipmap.emoji_bilibili_042,
        "[生病]" to R.mipmap.emoji_bilibili_043,
        "[吐]" to R.mipmap.emoji_bilibili_044,
        "[嘘声]" to R.mipmap.emoji_bilibili_045,
        "[捂眼]" to R.mipmap.emoji_bilibili_046,
        "[思考]" to R.mipmap.emoji_bilibili_047,
        "[再见]" to R.mipmap.emoji_bilibili_048,
        "[翻白眼]" to R.mipmap.emoji_bilibili_049,
        "[哈欠]" to R.mipmap.emoji_bilibili_050,
        "[奋斗]" to R.mipmap.emoji_bilibili_051,
        "[墨镜]" to R.mipmap.emoji_bilibili_052,
        "[难过]" to R.mipmap.emoji_bilibili_053,
        "[撇嘴]" to R.mipmap.emoji_bilibili_054,
        "[抓狂]" to R.mipmap.emoji_bilibili_055,
        "[生气]" to R.mipmap.emoji_bilibili_056,
        "[口罩]" to R.mipmap.emoji_bilibili_057,
        "[月饼]" to R.mipmap.emoji_bilibili_058,
        "[视频卫星]" to R.mipmap.emoji_bilibili_059,
        "[11周年]" to R.mipmap.emoji_bilibili_060,
        "[鸡腿]" to R.mipmap.emoji_bilibili_061,
        "[干杯]" to R.mipmap.emoji_bilibili_062,
        "[爱心]" to R.mipmap.emoji_bilibili_063,
        "[锦鲤]" to R.mipmap.emoji_bilibili_064,
        "[胜利]" to R.mipmap.emoji_bilibili_065,
        "[加油]" to R.mipmap.emoji_bilibili_066,
        "[保佑]" to R.mipmap.emoji_bilibili_067,
        "[抱拳]" to R.mipmap.emoji_bilibili_068,
        "[响指]" to R.mipmap.emoji_bilibili_069,
        "[支持]" to R.mipmap.emoji_bilibili_070,
        "[拥抱]" to R.mipmap.emoji_bilibili_071,
        "[怪我咯]" to R.mipmap.emoji_bilibili_072,
        "[跪了]" to R.mipmap.emoji_bilibili_073,
        "[黑洞]" to R.mipmap.emoji_bilibili_074,
        "[老鼠]" to R.mipmap.emoji_bilibili_075,
        "[2020]" to R.mipmap.emoji_bilibili_076,
        "[福到了]" to R.mipmap.emoji_bilibili_077,
        "[高兴]" to R.mipmap.emoji_bilibili_078,
        "[气愤]" to R.mipmap.emoji_bilibili_079,
        "[耍帅]" to R.mipmap.emoji_bilibili_080,
    )

    // 抖音 emoji 表情映射集合
    val douyinEmojiMap = mapOf(
        "[dy_V5]" to R.mipmap.emoji_dy_1,
        "[dy_给力]" to R.mipmap.emoji_dy_2,
        "[dy_嘿哈]" to R.mipmap.emoji_dy_3,
        "[dy_加好友]" to R.mipmap.emoji_dy_4,
        "[dy_勾引]" to R.mipmap.emoji_dy_5,
        "[dy_机智]" to R.mipmap.emoji_dy_6,
        "[dy_来看我]" to R.mipmap.emoji_dy_7,
        "[dy_灵机一动]" to R.mipmap.emoji_dy_8,
        "[dy_困]" to R.mipmap.emoji_dy_9,
        "[dy_疑问]" to R.mipmap.emoji_dy_10,
        "[dy_泣不成声]" to R.mipmap.emoji_dy_11,
        "[dy_小鼓掌]" to R.mipmap.emoji_dy_12,
        "[dy_发呆]" to R.mipmap.emoji_dy_13,
        "[dy_吐血]" to R.mipmap.emoji_dy_14,
        "[dy_酷拽]" to R.mipmap.emoji_dy_15,
        "[dy_泪奔]" to R.mipmap.emoji_dy_16,
        "[dy_抠鼻]" to R.mipmap.emoji_dy_17,
        "[dy_互粉]" to R.mipmap.emoji_dy_18,
        "[dy_去污粉]" to R.mipmap.emoji_dy_19,
        "[dy_666]" to R.mipmap.emoji_dy_20,
        "[dy_鼓掌]" to R.mipmap.emoji_dy_21,
        "[dy_憨笑]" to R.mipmap.emoji_dy_22,
        "[dy_笑哭]" to R.mipmap.emoji_dy_23,
        "[dy_哈欠]" to R.mipmap.emoji_dy_24,
        "[dy_震惊]" to R.mipmap.emoji_dy_25,
        "[dy_送心]" to R.mipmap.emoji_dy_26,
        "[dy_困惑]" to R.mipmap.emoji_dy_27,
        "[dy_打脸]" to R.mipmap.emoji_dy_28,
        "[dy_闭嘴]" to R.mipmap.emoji_dy_29,
        "[dy_无奈]" to R.mipmap.emoji_dy_30,
        "[dy_嘘]" to R.mipmap.emoji_dy_31,
        "[dy_一笑而过]" to R.mipmap.emoji_dy_32,
        "[dy_思考]" to R.mipmap.emoji_dy_33,
        "[dy_得意]" to R.mipmap.emoji_dy_34,
        "[dy_翻白眼]" to R.mipmap.emoji_dy_35,
        "[dy_愤怒]" to R.mipmap.emoji_dy_36,
        "[dy_大笑]" to R.mipmap.emoji_dy_37,
        "[dy_点赞]" to R.mipmap.emoji_dy_38,
        "[dy_摸头]" to R.mipmap.emoji_dy_39,
        "[dy_再见]" to R.mipmap.emoji_dy_40,
        "[dy_色]" to R.mipmap.emoji_dy_41,
        "[dy_流泪]" to R.mipmap.emoji_dy_42,
        "[dy_害羞]" to R.mipmap.emoji_dy_43,
        "[dy_大哭]" to R.mipmap.emoji_dy_44,
        "[dy_委屈]" to R.mipmap.emoji_dy_45,
        "[dy_调皮]" to R.mipmap.emoji_dy_46,
        "[dy_微笑]" to R.mipmap.emoji_dy_47,
        "[dy_猪头]" to R.mipmap.emoji_dy_48,
        "[dy_心]" to R.mipmap.emoji_dy_49,
        "[dy_太阳]" to R.mipmap.emoji_dy_50,
        "[dy_玫瑰]" to R.mipmap.emoji_dy_51,
        "[dy_拽]" to R.mipmap.emoji_dy_52,
        "[dy_惊恐]" to R.mipmap.emoji_dy_53,
        "[dy_流鼻血]" to R.mipmap.emoji_dy_54,
        "[dy_嘘声]" to R.mipmap.emoji_dy_55,
        "[dy_强]" to R.mipmap.emoji_dy_56,
        "[dy_弱]" to R.mipmap.emoji_dy_57,
        "[dy_如意]" to R.mipmap.emoji_dy_58,
        "[dy_握手]" to R.mipmap.emoji_dy_59,
        "[dy_胜利]" to R.mipmap.emoji_dy_60,
        "[dy_抱拳]" to R.mipmap.emoji_dy_61,
        "[dy_凋谢]" to R.mipmap.emoji_dy_62,
        "[dy_米饭]" to R.mipmap.emoji_dy_63,
        "[dy_蛋糕]" to R.mipmap.emoji_dy_64,
        "[dy_咖啡]" to R.mipmap.emoji_dy_65,
        "[dy_啤酒]" to R.mipmap.emoji_dy_66,
        "[dy_月亮]" to R.mipmap.emoji_dy_67,
        "[dy_便便]" to R.mipmap.emoji_dy_68,
        "[dy_拥抱]" to R.mipmap.emoji_dy_69,
        "[dy_刀]" to R.mipmap.emoji_dy_70,
        "[dy_炸弹]" to R.mipmap.emoji_dy_71,
        "[dy_威武]" to R.mipmap.emoji_dy_72,
        "[dy_篮球]" to R.mipmap.emoji_dy_73,
        "[dy_足球]" to R.mipmap.emoji_dy_74,
        "[dy_瓢虫]" to R.mipmap.emoji_dy_75,
        "[dy_勾引2]" to R.mipmap.emoji_dy_76,
        "[dy_OK]" to R.mipmap.emoji_dy_77,
        "[dy_爱你]" to R.mipmap.emoji_dy_78,
        "[dy_拳头]" to R.mipmap.emoji_dy_79,
        "[dy_合十]" to R.mipmap.emoji_dy_80,
        "[dy_捂脸]" to R.mipmap.emoji_dy_81,
        "[dy_大金牙]" to R.mipmap.emoji_dy_87,
        "[dy_偷笑]" to R.mipmap.emoji_dy_88,
        "[dy_石化]" to R.mipmap.emoji_dy_89,
        "[dy_可怜]" to R.mipmap.emoji_dy_91,
        "[dy_撇嘴]" to R.mipmap.emoji_dy_93,
        "[dy_尴尬]" to R.mipmap.emoji_dy_94,
        "[dy_生病]" to R.mipmap.emoji_dy_96,
        "[dy_奸笑]" to R.mipmap.emoji_dy_97,
        "[dy_坏笑]" to R.mipmap.emoji_dy_99,
        "[dy_抓狂]" to R.mipmap.emoji_dy_100,
        "[dy_钱]" to R.mipmap.emoji_dy_101,
        "[dy_亲亲]" to R.mipmap.emoji_dy_102,
        "[dy_恐惧]" to R.mipmap.emoji_dy_103,
        "[dy_愉快]" to R.mipmap.emoji_dy_104,
        "[dy_快哭了]" to R.mipmap.emoji_dy_106,
        "[dy_赞]" to R.mipmap.emoji_dy_108,
        "[dy_感谢]" to R.mipmap.emoji_dy_110,
        "[dy_嘴唇]" to R.mipmap.emoji_dy_111,
        "[dy_胡瓜]" to R.mipmap.emoji_dy_112,
        "[dy_我想静静]" to R.mipmap.emoji_dy_115,
        "[dy_飞吻]" to R.mipmap.emoji_dy_117,
        "[dy_听歌]" to R.mipmap.emoji_dy_119,
        "[dy_发怒]" to R.mipmap.emoji_dy_120,
        "[dy_绝望的凝视]" to R.mipmap.emoji_dy_121,
        "[dy_看]" to R.mipmap.emoji_dy_122,
        "[dy_熊吉]" to R.mipmap.emoji_dy_123,
        "[dy_骷髅]" to R.mipmap.emoji_dy_124,
        "[dy_黑脸]" to R.mipmap.emoji_dy_125,
        "[dy_呲牙]" to R.mipmap.emoji_dy_126,
        "[dy_吐]" to R.mipmap.emoji_dy_127,
        "[dy_流汗]" to R.mipmap.emoji_dy_128,
        "[dy_红脸]" to R.mipmap.emoji_dy_130,
        "[dy_尬笑]" to R.mipmap.emoji_dy_131,
        "[dy_做鬼脸]" to R.mipmap.emoji_dy_132,
        "[dy_睡]" to R.mipmap.emoji_dy_133,
        "[dy_惊喜]" to R.mipmap.emoji_dy_134,
        "[dy_敲打]" to R.mipmap.emoji_dy_135,
        "[dy_吐彩虹]" to R.mipmap.emoji_dy_136,
        "[dy_比心]" to R.mipmap.emoji_dy_138,
        "[dy_强壮]" to R.mipmap.emoji_dy_139,
        "[dy_碰拳]" to R.mipmap.emoji_dy_140,
    )

    val emojiMap get() = bilibiliEmojiMap + douyinEmojiMap

    fun getEmojiValue(key: String) = emojiMap[key] ?: 0
}